#ifndef GUARD_MINING_CONSTANTS
#define GUARD_MINING_CONSTANTS

/*********** OTHER ************/
#define MINING_ITEM_TILE_NONE           0
#define MINING_ITEM_TILE_DUG_UP         5
#define MINING_MAX_NUM_BURIED_ITEMS     4
#define MINING_COUNT_MAX_NUMBER_STONES  2

/*********** SOUNDS ************/
#define MINING_SE_HIT_HAMMER            SE_M_ROCK_THROW
#define MINING_SE_HIT_PICKAXE           SE_M_DIG
#define MINING_SE_HIT_AIR               SE_M_WING_ATTACK
#define MINING_SE_HIT_DUG_UP            SE_ICE_STAIRS
#define MINING_SE_WALL_COLLAPSE         SE_M_EARTHQUAKE
#define MINING_SE_TOOL_SWITCH           SE_ROTATING_GATE
#define MINING_SE_ITEM_SPARKLE          SE_RG_CARD_OPEN

/*********** ITEM SPRITE TAGS ************/
enum
{
    MINING_TAG_ITEM_HEARTSCALE = 12,
    MINING_TAG_ITEM_HARDSTONE,
    MINING_TAG_ITEM_REVIVE,
    MINING_TAG_ITEM_STAR_PIECE,
    MINING_TAG_ITEM_DAMP_ROCK,
    MINING_TAG_ITEM_RED_SHARD,
    MINING_TAG_ITEM_BLUE_SHARD,
    MINING_TAG_ITEM_IRON_BALL,
    MINING_TAG_ITEM_REVIVE_MAX,
    MINING_TAG_ITEM_EVER_STONE,
    MINING_TAG_ITEM_OVAL_STONE,
    MINING_TAG_ITEM_LIGHT_CLAY,
    MINING_TAG_ITEM_HEAT_ROCK,
    MINING_TAG_ITEM_ICY_ROCK,
    MINING_TAG_ITEM_SMOOTH_ROCK,
    MINING_TAG_ITEM_YELLOW_SHARD,
    MINING_TAG_ITEM_GREEN_SHARD,
    MINING_TAG_ITEM_LEAF_STONE,
    MINING_TAG_ITEM_FIRE_STONE,
    MINING_TAG_ITEM_WATER_STONE,
    MINING_TAG_ITEM_THUNDER_STONE,
    MINING_TAG_ITEM_MOON_STONE,
    MINING_TAG_ITEM_SUN_STONE,
    MINING_TAG_ITEM_ODD_KEY_STONE,
    MINING_TAG_ITEM_SKULL_FOSSIL,
    MINING_TAG_ITEM_ARMOR_FOSSIL,

    MINING_TAG_STONE_1X4,
    MINING_TAG_STONE_4X1,
    MINING_TAG_STONE_2X4,
    MINING_TAG_STONE_4X2,
    MINING_TAG_STONE_2X2,
    MINING_TAG_STONE_3X3,
    MINING_TAG_STONE_SNAKE1,
    MINING_TAG_STONE_SNAKE2,
    MINING_TAG_STONE_MUSHROOM1,
    MINING_TAG_STONE_MUSHROOM2,
};

/*********** FLAGS ************/
#define FLAG_USE_DEFAULT_MESSAGE_BOX            FALSE

/*********** DEBUG FLAGS ************/
#define DEBUG_ENABLE_ITEM_GENERATION_OPTIONS    FALSE

enum
{
    MININGID_NONE,
    MININGID_STONE_1x4,
    MININGID_STONE_4x1,
    MININGID_STONE_2x4,
    MININGID_STONE_4x2,
    MININGID_STONE_2x2,
    MININGID_STONE_3x3,
    MININGID_STONE_SNAKE1,
    MININGID_STONE_SNAKE2,
    MININGID_STONE_MUSHROOM1,
    MININGID_STONE_MUSHROOM2,
    MININGID_HEART_SCALE,
    MININGID_HARD_STONE,
    MININGID_REVIVE,
    MININGID_STAR_PIECE,
    MININGID_DAMP_ROCK,
    MININGID_RED_SHARD,
    MININGID_BLUE_SHARD,
    MININGID_IRON_BALL,
    MININGID_REVIVE_MAX,
    MININGID_EVER_STONE,
    MININGID_OVAL_STONE,
    MININGID_LIGHT_CLAY,
    MININGID_HEAT_ROCK,
    MININGID_ICY_ROCK,
    MININGID_SMOOTH_ROCK,
    MININGID_YELLOW_SHARD,
    MININGID_GREEN_SHARD,
    MININGID_LEAF_STONE,
    MININGID_FIRE_STONE,
    MININGID_WATER_STONE,
    MININGID_THUNDER_STONE,
    MININGID_MOON_STONE,
    MININGID_SUN_STONE,
    MININGID_ODD_KEY_STONE,
    MININGID_SKULL_FOSSIL,
    MININGID_ARMOR_FOSSIL,
};

#define MINING_COUNT_ID_STONE           MININGID_STONE_MUSHROOM2

#define MINING_ZONE_WIDTH 12
#define MINING_ZONE_HEIGHT 8

#define MINING_ZONE_1_X_LEFT_BOUNDARY     0
#define MINING_ZONE_1_X_RIGHT_BOUNDARY    5
#define MINING_ZONE_1_Y_UP_BOUNDARY       0
#define MINING_ZONE_1_Y_DOWN_BOUNDARY     3

#define MINING_ZONE_2_X_LEFT_BOUNDARY     0
#define MINING_ZONE_2_X_RIGHT_BOUNDARY    5
#define MINING_ZONE_2_Y_UP_BOUNDARY       4
#define MINING_ZONE_2_Y_DOWN_BOUNDARY     MINING_ZONE_HEIGHT - 1

#define MINING_ZONE_3_X_LEFT_BOUNDARY     6
#define MINING_ZONE_3_X_RIGHT_BOUNDARY    MINING_ZONE_WIDTH - 1
#define MINING_ZONE_3_Y_UP_BOUNDARY       0
#define MINING_ZONE_3_Y_DOWN_BOUNDARY     3

#define MINING_ZONE_4_X_LEFT_BOUNDARY     6
#define MINING_ZONE_4_X_RIGHT_BOUNDARY    MINING_ZONE_WIDTH - 1
#define MINING_ZONE_4_Y_UP_BOUNDARY       4
#define MINING_ZONE_4_Y_DOWN_BOUNDARY     MINING_ZONE_HEIGHT - 1

/*********** MINING LOCATION IDs ************/
//Test Locations
#define LOCATIONID_TEST_0           0
#define LOCATIONID_TEST_1           1
#define LOCATIONID_TEST_2           2
#define LOCATIONID_TEST_3           3
#define LOCATIONID_TEST_4           4
#define LOCATIONID_TEST_5           5
#define LOCATIONID_TEST_6           6
#define LOCATIONID_TEST_7           7
#define LOCATIONID_TEST_8           8
#define LOCATIONID_TEST_9           9
// Towns
#define LOCATIONID_PETALBURGCITY_0  10
#define LOCATIONID_PETALBURGCITY_1  11
#define LOCATIONID_SLATEPORTCITY_0  20
#define LOCATIONID_MAUVILLECITY_0   30
#define LOCATIONID_RUSTBOROCITY_0   40
#define LOCATIONID_FORTREECITY_0    50
#define LOCATIONID_LILYCOVECITY_0   60
#define LOCATIONID_LILYCOVECITY_1   61
#define LOCATIONID_MOSSDEEPCITY_0   70
#define LOCATIONID_MOSSDEEPCITY_1   71
#define LOCATIONID_MOSSDEEPCITY_2   72
#define LOCATIONID_SOOTOPOLISCITY_0 80
#define LOCATIONID_SOOTOPOLISCITY_1 81
#define LOCATIONID_EVERGRANDECITY_0 90
#define LOCATIONID_LITTLEROOTTOWN_0 100
#define LOCATIONID_OLDDALETOWN_0    110
#define LOCATIONID_DEWFORDTOWN_0    120
#define LOCATIONID_LAVARIDGETOWN_0  130
#define LOCATIONID_FALLARBORTOWN_0  140
#define LOCATIONID_VERDANTURFTOWN_0 150
#define LOCATIONID_PACIFIDLOGTOWN_0 160
// Routes
#define LOCATIONID_ROUTE_101_0      1010
#define LOCATIONID_ROUTE_102_0      1020
#define LOCATIONID_ROUTE_103_0      1030
#define LOCATIONID_ROUTE_104_0      1040
#define LOCATIONID_ROUTE_105_0      1050
#define LOCATIONID_ROUTE_106_0      1060
#define LOCATIONID_ROUTE_107_0      1070
#define LOCATIONID_ROUTE_108_0      1080
#define LOCATIONID_ROUTE_109_0      1090
#define LOCATIONID_ROUTE_109_1      1091
#define LOCATIONID_ROUTE_110_0      1100
#define LOCATIONID_ROUTE_111_0      1110
#define LOCATIONID_ROUTE_112_0      1120
#define LOCATIONID_ROUTE_113_0      1130
#define LOCATIONID_ROUTE_114_0      1140
#define LOCATIONID_ROUTE_114_1      1141
#define LOCATIONID_ROUTE_114_2      1142
#define LOCATIONID_ROUTE_115_0      1150
#define LOCATIONID_ROUTE_116_0      1160
#define LOCATIONID_ROUTE_117_0      1170
#define LOCATIONID_ROUTE_118_0      1180
#define LOCATIONID_ROUTE_119_0      1190
#define LOCATIONID_ROUTE_119_1      1191
#define LOCATIONID_ROUTE_120_0      1200
#define LOCATIONID_ROUTE_121_0      1210
#define LOCATIONID_ROUTE_122_0      1220
#define LOCATIONID_ROUTE_123_0      1230
#define LOCATIONID_ROUTE_124_0      1240
#define LOCATIONID_ROUTE_125_0      1250
#define LOCATIONID_ROUTE_126_0      1260
#define LOCATIONID_ROUTE_127_0      1270
#define LOCATIONID_ROUTE_128_0      1280
#define LOCATIONID_ROUTE_129_0      1290
#define LOCATIONID_ROUTE_130_0      1300
#define LOCATIONID_ROUTE_131_0      1310
#define LOCATIONID_ROUTE_132_0      1320
#define LOCATIONID_ROUTE_133_0      1330
#define LOCATIONID_ROUTE_134_0      1340
// Dungeons
#define LOCATIONID_METEORFALLS_0    2000
#define LOCATIONID_RUSTURFTUNNEL_0  2010
#define LOCATIONID_GRANITECAVE_0    2020
#define LOCATIONID_PETALBURGWOODS_0 2030
#define LOCATIONID_PETALBURGWOODS_1 2031
#define LOCATIONID_PETALBURGWOODS_2 2032
#define LOCATIONID_MTCHIMNEY_0      2040
#define LOCATIONID_MTCHIMNEY_1      2041
#define LOCATIONID_MTCHIMNEY_2      2042
#define LOCATIONID_JAGGEDPASS_0     2050
#define LOCATIONID_JAGGEDPASS_1     2051
#define LOCATIONID_FIERYPATH_0      2060
#define LOCATIONID_MTPYRE_0         2070
#define LOCATIONID_VICTORYROAD_0    2080
#define LOCATIONID_SHOALCAVE_0      2090
#define LOCATIONID_SKYPILLAR_0      2100
#define LOCATIONID_MIRAGETOWER_0    2110
#define LOCATIONID_SANDYCAVES_0     2120
#define LOCATIONID_SANDYCAVES_1     2121
#define LOCATIONID_SANDYCAVES_2     2122
#define LOCATIONID_SANDYCAVES_3     2123
#define LOCATIONID_NEWMAUVILLE_0    2130
#define LOCATIONID_ABANDONEDSHIP_0  2140

#endif
