#!/usr/bin/env python3
"""Generate src/data/pokemon/g_species_family.h from per-gen family headers.

Algorithm:
- For each file under src/data/pokemon/species_info matching gen_*_families.h
- Find blocks guarded by `#if P_FAMILY_...` ... `#endif` and collect all `[SPECIES_...]` entries inside.
- Use the first `SPECIES_...` in the block as the family leader and map all species in the block to that leader.
- Emit a C header with designated initializers: `[SPECIES_X] = SPECIES_LEADER,`

This script is intentionally tolerant of nested preprocessor conditionals and comments.
"""
import re
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SPECIES_INFO_DIR = ROOT / 'src' / 'data' / 'pokemon' / 'species_info'
OUT_PATH = ROOT / 'src' / 'data' / 'pokemon' / 'g_species_family.h'

def find_family_files():
    return sorted(SPECIES_INFO_DIR.glob('gen_*_families.h'))

SPECIES_RE = re.compile(r"\[SPECIES_([A-Z0-9_]+)\]")
FAMILY_IF_RE = re.compile(r"#\s*if\s+P_FAMILY_([A-Za-z0-9_]+)")
FAMILY_END_RE = re.compile(r"#\s*endif\b")

def parse_file(path, mapping):
    with path.open('r', encoding='utf-8', errors='ignore') as f:
        in_family_block = False
        leader = None
        nested_if_depth = 0
        for line in f:
            m = FAMILY_IF_RE.search(line)
            if m:
                # Enter a P_FAMILY block
                in_family_block = True
                leader = None
                nested_if_depth = 1
                continue

            if in_family_block:
                # track nested #if/#endif to know when block ends
                if line.strip().startswith('#if'):
                    nested_if_depth += 1
                if line.strip().startswith('#endif'):
                    nested_if_depth -= 1
                    if nested_if_depth <= 0:
                        in_family_block = False
                        leader = None
                        nested_if_depth = 0
                        continue

                for sm in SPECIES_RE.finditer(line):
                    species = sm.group(1)
                    if leader is None:
                        leader = species
                    mapping[species] = leader

def build_mapping():
    mapping = {}
    files = find_family_files()
    if not files:
        print('No gen_*_families.h files found under', SPECIES_INFO_DIR, file=sys.stderr)
        return mapping
    for p in files:
        parse_file(p, mapping)
    return mapping

def emit_header(mapping):
    lines = []
    lines.append('/* This file is autogenerated by tools/gen_family_table.py — do not edit. */')
    lines.append('#ifndef GUARD_DATA_POKEMON_G_SPECIES_FAMILY_H')
    lines.append('#define GUARD_DATA_POKEMON_G_SPECIES_FAMILY_H')
    lines.append('')
    lines.append('#include "global.h"')
    lines.append('')
    lines.append('const u16 gSpeciesFamily[NUM_SPECIES] =')
    lines.append('{')
    # Always provide a default for SPECIES_NONE
    lines.append('    [SPECIES_NONE] = SPECIES_NONE,')
    # Sort species by name for deterministic output
    for species in sorted(mapping.keys()):
        leader = mapping[species]
        lines.append(f'    [SPECIES_{species}] = SPECIES_{leader},')
    lines.append('};')
    lines.append('')
    lines.append('#endif // GUARD_DATA_POKEMON_G_SPECIES_FAMILY_H')
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open('w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print('Wrote', OUT_PATH)

def main():
    mapping = build_mapping()
    if not mapping:
        print('Warning: empty mapping — no species parsed', file=sys.stderr)
    emit_header(mapping)

if __name__ == '__main__':
    main()
